import type { Lab } from "./types";

export const labs: Lab[] = [
  {
    slug: "jwt-exploit-chain",
    title: "JWT Exploitation Chain",
    category: "Auth",
    difficulty: "Medium",
    durationMinutes: 90,
    xp: 350,
    stage: "available",
    summary:
      "Walk through alg confusion, weak-secret recovery, and kid-header injection against a vulnerable Node.js API.",
    tags: ["JWT", "alg:none", "Key Confusion"],
    body: `This lab chains three JWT weaknesses into an authentication bypass against a deliberately vulnerable practice target:\n\n1. Algorithm confusion (HS256 ↔ RS256)\n2. Weak HMAC secret brute-forcing with hashcat\n3. \`kid\` header SQL injection / path traversal\n\nThe goal is not to memorize payloads — it is to understand *why* each of these classes exists, and what a correct JWT verification routine looks like.`,
  },
  {
    slug: "ssrf-to-cloud-metadata",
    title: "SSRF to Cloud Metadata",
    category: "Cloud",
    difficulty: "Medium",
    durationMinutes: 120,
    xp: 400,
    stage: "build",
    summary: "Chain an unvalidated URL fetch to the cloud metadata service and extract role credentials.",
    tags: ["SSRF", "IMDSv1", "AWS"],
  },
  {
    slug: "graphql-introspection-abuse",
    title: "GraphQL Introspection Abuse",
    category: "Web",
    difficulty: "Easy",
    durationMinutes: 45,
    xp: 200,
    stage: "build",
    summary: "Discover hidden endpoints and sensitive fields through unrestricted GraphQL introspection.",
    tags: ["GraphQL", "Introspection"],
  },
  {
    slug: "oauth-redirect-bypass",
    title: "OAuth Redirect URI Bypass",
    category: "Auth",
    difficulty: "Medium",
    durationMinutes: 75,
    xp: 350,
    stage: "build",
    summary: "Take over accounts via subtle flaws in OAuth redirect URI validation logic.",
    tags: ["OAuth", "Account Takeover"],
  },
  {
    slug: "deserialization-rce",
    title: "Deserialization RCE",
    category: "Web",
    difficulty: "Hard",
    durationMinutes: 180,
    xp: 500,
    stage: "planned",
    summary: "Craft a malicious serialized object to achieve remote code execution on a Java application.",
    tags: ["Deserialization", "RCE", "ysoserial"],
  },
  {
    slug: "prompt-injection-basics",
    title: "Prompt Injection Basics",
    category: "AI",
    difficulty: "Easy",
    durationMinutes: 40,
    xp: 200,
    stage: "build",
    summary: "Walk an LLM-backed assistant through escalating prompt-injection vectors and harden its system prompt.",
    tags: ["LLM", "Prompt Injection"],
  },
  {
    slug: "kerberoasting-lab",
    title: "Kerberoasting in Active Directory",
    category: "Auth",
    difficulty: "Medium",
    durationMinutes: 120,
    xp: 400,
    stage: "planned",
    summary: "Extract service tickets, crack them offline, and pivot via a weak service account.",
    tags: ["Active Directory", "Kerberos"],
  },
  {
    slug: "container-escape",
    title: "Container Escape via runc",
    category: "Cloud",
    difficulty: "Hard",
    durationMinutes: 150,
    xp: 500,
    stage: "planned",
    summary: "Break out of a privileged container by abusing a classic runc file-descriptor bug.",
    tags: ["Container", "runc", "Escape"],
  },
];

export function getLab(slug: string) {
  return labs.find((l) => l.slug === slug);
}
